BTC/USD : {
  mintick: 1, 
  minsize: 0.0001,
  size: 0.0001, 
  sigma: 2,
  fade: 0.001,
  lookback: 60,
}
ETH/USD : {
  mintick: .1, 
  minsize: 0.001, 
  size: 0.001, 
  sigma: 2,
  fade: 0.001,
  lookback: 60,
}
SOL/USD: {
  mintick: 0.0025,
  minsize: 0.01,
  size: 0.01,
  sigma: 2,
  fade: 0.001,
  lookback: 60,
}